name: Deploy Pixel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get the latest code
      uses: actions/checkout@v3
      
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        script: |
          cd /home/slicedpixel/domains/pixel.slicedpixel.com/
          git pull origin main
          git status
          pm2 restart pixel --watch